name: Action CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
      - uses: sergeysova/docker-publish-action@master
        with:
          image: sergeysova/docker-publish-action/test
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_semver: 'skip'
          semver_higher: true
